In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("../data/raw/girona_energy_certificates.csv")

df.head()

,census_tract,metres_cadastre,emissions_de_co2,qual_energia,qual_emissions,data_entrada,motiu,us_edifici,zona_climatica,energia_primaria,cost_energia
0,1707903003,45.00,29.35,E,NaN,NaN,Lloguer,Habitatge individual en bloc d'habitatges,D2,118.06,NaN
1,1707902010,54.66,41.30,E,NaN,2015-10-01,Lloguer,Habitatge individual en bloc d'habitatges,D2,166.09,591.56
2,1707902018,77.10,14.89,D,NaN,2015-09-01,Lloguer,Habitatge individual en bloc d'habitatges,D2,72.47,NaN
3,1707902019,145.75,75.78,F,NaN,2016-07-01,Compravenda,Habitatge unifamiliar,D2,292.12,NaN
4,1707902002,73.00,30.39,E,NaN,NaN,Lloguer,Habitatge individual en bloc d'habitatges,D2,145.32,630.83

In [9]:
df = pd.read_csv("../data/raw/girona_for_rent_synthetic.csv")

df.head()

,synthetic_id,year_available,address,price,area,rooms,neighbourhood,floors,elevator,lat,lon
0,2015-0001,2015,"Calle de Santiago, 62",1145,62,2,Migdia Casernes,1,False,41.968318,2.816188
1,2015-0002,2015,"Calle de Sant Agustí, 42",695,67,2,Migdia Casernes,4,True,41.970975,2.821103
2,2015-0003,2015,"Calle Mare de Déu del Remei, 11",755,91,4,Sant Narcís,2,True,41.976793,2.812300
3,2015-0004,2015,"Calle Bonastruc de Porta, 67",755,104,3,Devesa,1,False,41.984938,2.819815
4,2015-0005,2015,"Calle Jocs Olímpics de Barcelona, 33",1020,86,3,Palau,0,True,41.958326,2.820114

In [10]:
df = pd.read_csv("../data/raw/girona_for_rent.csv")

df.head()

,address,price,area,rooms,neighbourhood,floors,elevator,lat,lon
0,"Calle Doctor Pascual i Prats, 1",750,50,1.0,Carme-Vistalegre,1.0,False,41.976921,2.824609
1,Ronda Ferran Puig,1350,108,3.0,Devesa,4.0,True,41.985110,2.817030
2,"Calle de les Ballesteries, 15",1020,87,1.0,Barri Vell,3.0,False,41.985732,2.824890
3,"Calle del Riu Güell, 3",2700,190,2.0,Devesa,3.0,True,41.985791,2.819352
4,"Calle Barcelona, 43",2200,100,3.0,Eixample,4.0,True,41.978423,2.818067

In [11]:
df = pd.read_csv("../data/raw/girona_services.csv")

df.head()

,id,name,category,subtype,lat,lon
0,31022931,NaN,mobility,platform,41.964253,2.831639
1,250105520,c. Barcelona / c. Caldes de Montbui,mobility,platform,41.971805,2.814933
2,354612955,NaN,mobility,platform,41.976633,2.802304
3,354880351,NaN,mobility,platform,41.956935,2.820036
4,354880430,NaN,mobility,platform,41.962500,2.832221

In [12]:
df = pd.read_csv("../data/raw/girona_sociodemographic.csv")
print(df.columns)
df.head()

Index(['census_tract', 'year', 'fuente_de_ingreso_otras_prestaciones',
       'fuente_de_ingreso_otros_ingresos', 'fuente_de_ingreso_pensiones',
       'fuente_de_ingreso_prestaciones_por_desempleo',
       'fuente_de_ingreso_salario', 'distribucion_de_la_renta_p80_p20',
       'indice_de_gini', 'media_de_la_renta_por_unidad_de_consumo',
       'mediana_de_la_renta_por_unidad_de_consumo',
       'renta_bruta_media_por_hogar', 'renta_bruta_media_por_persona',
       'renta_neta_media_por_hogar', 'renta_neta_media_por_persona',
       'edad_media_de_la_poblacion', 'poblacion',
       'porcentaje_de_hogares_unipersonales',
       'porcentaje_de_poblacion_de_65_y_mas_anos',
       'porcentaje_de_poblacion_espanola',
       'porcentaje_de_poblacion_menor_de_18_anos', 'tamano_medio_del_hogar'],
      dtype='str')

,census_tract,year,fuente_de_ingreso_otras_prestaciones,fuente_de_ingreso_otros_ingresos,fuente_de_ingreso_pensiones,fuente_de_ingreso_prestaciones_por_desempleo,fuente_de_ingreso_salario,distribucion_de_la_renta_p80_p20,indice_de_gini,media_de_la_renta_por_unidad_de_consumo,...,renta_bruta_media_por_persona,renta_neta_media_por_hogar,renta_neta_media_por_persona,edad_media_de_la_poblacion,poblacion,porcentaje_de_hogares_unipersonales,porcentaje_de_poblacion_de_65_y_mas_anos,porcentaje_de_poblacion_espanola,porcentaje_de_poblacion_menor_de_18_anos,tamano_medio_del_hogar
0,1707901001,2015,1.8,20.4,13.8,2.0,62.1,3.3,39.6,19430.0,...,16565.0,28954.0,13196.0,39.1,1020.0,44.6,13.2,84.6,17.2,2.2
1,1707901001,2016,2.0,21.9,13.9,1.6,60.6,3.7,38.9,20791.0,...,17729.0,30986.0,14222.0,39.7,1019.0,45.3,13.4,86.7,16.8,2.1
2,1707901001,2017,2.2,21.0,11.9,1.5,63.4,3.6,39.3,21255.0,...,18396.0,31846.0,14616.0,39.3,1029.0,45.1,12.4,85.3,16.8,2.1
3,1707901001,2018,2.4,22.5,10.3,1.4,63.5,3.9,39.5,22320.0,...,19265.0,34048.0,15256.0,39.2,1062.0,43.5,12.0,82.4,16.0,2.2
4,1707901001,2019,2.6,21.4,11.1,1.6,63.3,3.6,39.9,23505.0,...,20010.0,35668.0,15955.0,39.2,1074.0,42.4,11.6,79.3,14.8,2.2

In [13]:
df.iloc[0]

census_tract                                    1.707901e+09
year                                            2.015000e+03
fuente_de_ingreso_otras_prestaciones            1.800000e+00
fuente_de_ingreso_otros_ingresos                2.040000e+01
fuente_de_ingreso_pensiones                     1.380000e+01
fuente_de_ingreso_prestaciones_por_desempleo    2.000000e+00
fuente_de_ingreso_salario                       6.210000e+01
distribucion_de_la_renta_p80_p20                3.300000e+00
indice_de_gini                                  3.960000e+01
media_de_la_renta_por_unidad_de_consumo         1.943000e+04
mediana_de_la_renta_por_unidad_de_consumo       1.540000e+04
renta_bruta_media_por_hogar                     3.634900e+04
renta_bruta_media_por_persona                   1.656500e+04
renta_neta_media_por_hogar                      2.895400e+04
renta_neta_media_por_persona                    1.319600e+04
edad_media_de_la_poblacion                      3.910000e+01
poblacion                                       1.020000e+03
porcentaje_de_hogares_unipersonales             4.460000e+01
porcentaje_de_poblacion_de_65_y_mas_anos        1.320000e+01
porcentaje_de_poblacion_espanola                8.460000e+01
porcentaje_de_poblacion_menor_de_18_anos        1.720000e+01
tamano_medio_del_hogar                          2.200000e+00
Name: 0, dtype: float64